name: CI

on:
  push:
    branches:
      - content 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Add theme in git submodule
      run: git submodule add https://github.com/chipzoller/hugo-clarity themes/hugo-clarity
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: Build
      run: hugo --minify

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: publish_on_github_pages
        FOLDER: public